"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Powers;
(function (Powers) {
    Powers["NegativeOne"] = "-1";
    Powers["Star"] = "*";
    Powers["Infinity"] = "\u221E";
    Powers["StarSquared"] = "*\u00B2";
    Powers["QuestionMark"] = "?";
    Powers["Zero"] = "0";
    Powers["PlusZero"] = "+0";
    Powers["OneHalf"] = ".5";
    Powers["PlusOne"] = "+1";
    Powers["One"] = "1";
    Powers["OnePlusStar"] = "1+*";
    Powers["OneAndOneHalf"] = "1.5";
    Powers["Two"] = "2";
    Powers["TwoPlusStar"] = "2+*";
    Powers["PlusTwo"] = "+2";
    Powers["TwoAndOneHalf"] = "2.5";
    Powers["PlusThree"] = "+3";
    Powers["Three"] = "3";
    Powers["ThreeAndOneHalf"] = "3.5";
    Powers["PlusFour"] = "+4";
    Powers["Four"] = "4";
    Powers["Five"] = "5";
    Powers["Six"] = "6";
    Powers["Seven"] = "7";
    Powers["Eight"] = "8";
    Powers["Nine"] = "9";
    Powers["Ten"] = "10";
    Powers["Eleven"] = "11";
    Powers["Twelve"] = "12";
    Powers["Thirteen"] = "13";
    Powers["Fifteen"] = "15";
    Powers["Twenty"] = "20";
    Powers["NinetyNine"] = "99";
})(Powers = exports.Powers || (exports.Powers = {}));
//# sourceMappingURL=powers.js.map