"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Toughnesses;
(function (Toughnesses) {
    Toughnesses["NegativeOne"] = "-1";
    Toughnesses["Star"] = "*";
    Toughnesses["StarSquared"] = "*\u00B2";
    Toughnesses["QuestionMark"] = "?";
    Toughnesses["Zero"] = "0";
    Toughnesses["MinusZero"] = "-0";
    Toughnesses["PlusZero"] = "+0";
    Toughnesses["OneHalf"] = ".5";
    Toughnesses["PlusOne"] = "+1";
    Toughnesses["One"] = "1";
    Toughnesses["OnePlusStar"] = "1+*";
    Toughnesses["OneAndOneHalf"] = "1.5";
    Toughnesses["Two"] = "2";
    Toughnesses["TwoPlusStar"] = "2+*";
    Toughnesses["PlusTwo"] = "+2";
    Toughnesses["TwoAndOneHalf"] = "2.5";
    Toughnesses["PlusThree"] = "+3";
    Toughnesses["Three"] = "3";
    Toughnesses["ThreeAndOneHalf"] = "3.5";
    Toughnesses["PlusFour"] = "+4";
    Toughnesses["Four"] = "4";
    Toughnesses["Five"] = "5";
    Toughnesses["Six"] = "6";
    Toughnesses["SevenMinusStar"] = "7-*";
    Toughnesses["Seven"] = "7";
    Toughnesses["Eight"] = "8";
    Toughnesses["Nine"] = "9";
    Toughnesses["Ten"] = "10";
    Toughnesses["Eleven"] = "11";
    Toughnesses["Twelve"] = "12";
    Toughnesses["Thirteen"] = "13";
    Toughnesses["Fourteen"] = "14";
    Toughnesses["Fifteen"] = "15";
    Toughnesses["Twenty"] = "20";
    Toughnesses["NinetyNine"] = "99";
})(Toughnesses = exports.Toughnesses || (exports.Toughnesses = {}));
//# sourceMappingURL=toughnesses.js.map