"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Watermarks;
(function (Watermarks) {
    Watermarks["Abzan"] = "abzan";
    Watermarks["AgentsOfSneak"] = "agentsofsneak";
    Watermarks["Arena"] = "arena";
    Watermarks["Atarka"] = "atarka";
    Watermarks["Azorius"] = "azorius";
    Watermarks["Boros"] = "boros";
    Watermarks["ColorPie"] = "colorpie";
    Watermarks["Conspiracy"] = "conspiracy";
    Watermarks["CrossbreedLabs"] = "crossbreedlabs";
    Watermarks["DCI"] = "dci";
    Watermarks["DAndD"] = "d&d";
    Watermarks["Dimir"] = "dimir";
    Watermarks["Dromoka"] = "dromoka";
    Watermarks["FNM"] = "fnm";
    Watermarks["GoblinExplosioneers"] = "goblinexplosioneers";
    Watermarks["Golgari"] = "golgari";
    Watermarks["GrandPrix"] = "grandprix";
    Watermarks["Gruul"] = "gruul";
    Watermarks["Izzet"] = "izzet";
    Watermarks["Jeskai"] = "jeskai";
    Watermarks["Junior"] = "junior";
    Watermarks["JuniorAPAC"] = "juniorapac";
    Watermarks["JuniorEurope"] = "junioreurope";
    Watermarks["Kolaghan"] = "kolaghan";
    Watermarks["LeagueOfDastardlyDoom"] = "leagueofdastardlydoom";
    Watermarks["Mardu"] = "mardu";
    Watermarks["Mirran"] = "mirran";
    Watermarks["MPS"] = "mps";
    Watermarks["MTG"] = "mtg";
    Watermarks["MTGTen"] = "mtg10";
    Watermarks["MTGFifteen"] = "mtg15";
    Watermarks["Nerf"] = "nerf";
    Watermarks["Ojutai"] = "ojutai";
    Watermarks["OrderOfTheWidget"] = "orderofthewidget";
    Watermarks["Orzhov"] = "orzhov";
    Watermarks["Phyrexian"] = "phyrexian";
    Watermarks["Planeswalker"] = "planeswalker";
    Watermarks["ProTour"] = "protour";
    Watermarks["Rakdos"] = "rakdos";
    Watermarks["Scholarship"] = "scholarship";
    Watermarks["Selesnya"] = "selesnya";
    Watermarks["Set"] = "set";
    Watermarks["Silumgar"] = "silumgar";
    Watermarks["Simic"] = "simic";
    Watermarks["Sultai"] = "sultai";
    Watermarks["Temur"] = "temur";
    Watermarks["Transformers"] = "transformers";
    Watermarks["WotC"] = "wotc";
    Watermarks["WPN"] = "wpn";
})(Watermarks = exports.Watermarks || (exports.Watermarks = {}));
//# sourceMappingURL=watermarks.js.map